name: remote_config_firebase
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_remote_config: ^4.2.5
  firebase_analytics: ^10.4.5
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  package_info_plus: ^4.1.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

