// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJtgUe2R3U6_DAWS3ZID6-3Cp7H1G3_pc',
    appId: '1:986675450355:web:6708b8fb014e27fb0c4286',
    messagingSenderId: '986675450355',
    projectId: 'rempte-config',
    authDomain: 'rempte-config.firebaseapp.com',
    storageBucket: 'rempte-config.appspot.com',
    measurementId: 'G-5TXXYEKL6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD3gqb9KLjYjFrO80pFg_IwhhAdpXCLoE',
    appId: '1:986675450355:android:aedfc10cc8bd0bc90c4286',
    messagingSenderId: '986675450355',
    projectId: 'rempte-config',
    storageBucket: 'rempte-config.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-ONQF2_u9qpUKo3xWwYAPh3aNaSWy9ZU',
    appId: '1:986675450355:ios:3497300cc78f52950c4286',
    messagingSenderId: '986675450355',
    projectId: 'rempte-config',
    storageBucket: 'rempte-config.appspot.com',
    iosClientId: '986675450355-jpcpispad400tk4s3cg91mq0mn3bnfdq.apps.googleusercontent.com',
    iosBundleId: 'com.example.remoteConfigFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-ONQF2_u9qpUKo3xWwYAPh3aNaSWy9ZU',
    appId: '1:986675450355:ios:0767d58d3227ac440c4286',
    messagingSenderId: '986675450355',
    projectId: 'rempte-config',
    storageBucket: 'rempte-config.appspot.com',
    iosClientId: '986675450355-r1gsh49kmlkt9pr5es5i5kebptdlnds4.apps.googleusercontent.com',
    iosBundleId: 'com.example.remoteConfigFirebase.RunnerTests',
  );
}
